import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { cn } from "@/lib/utils";
import InitialProvider from "@/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../public/fonts/pretendard-variable.woff2",
  variable: "--pretendard-font",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className={cn("antialiased", pretendard.className)}>
        <InitialProvider>{children}</InitialProvider>
      </body>
    </html>
  );
}
